# Generated by Django 4.2.5 on 2024-02-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metro_station',
            name='USER',
        ),
    ]
