# Generated by Django 4.2.5 on 2024-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_metro_station_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
