# Generated by Django 4.2.5 on 2024-02-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_boat_user_remove_boat_status_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
