# Generated by Django 4.2.5 on 2024-02-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_schedule_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
                ('paydate', models.CharField(max_length=100)),
                ('paystatus', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
