# Generated by Django 4.2.5 on 2024-02-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
